apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-sa-role
rules:
- apiGroups: ["","apps"]
  resources: ["nodes", "namespaces", "pods", "services", "deployments", "replicasets", "configmaps", "secrets", "statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]